networks:
  interactive_net:
    external: true

services:
  leadshub_api:
    image: jsglobaltech/leadhub_webapi
    container_name: leadshub_Api
    restart: always
    build:
      context: .
      dockerfile: Services/LeadsHub/LeadsHub.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      interactive_net:
        ipv4_address: 172.19.0.11
    expose:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # whatsapp_api:
  #   image: ${DOCKER_REGISTRY-}whatsappapi
  #   container_name: whatsapp_api
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Integrations/WhatsApp/WhatsApp.Api/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ASPNETCORE_HTTP_PORTS=8080
  #    ## - ASPNETCORE_HTTPS_PORTS=8081
  #   networks:
  #     interactive_net:
  #       ipv4_address: 172.19.0.12
  #   ports:
  #     - "7000:8080"
  #     - "7001:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro