networks:
  interactive_net:
    name: interactive_net 
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  interactive_data:
  pgadmin4:
  rabbitmq_data:

services:
  leadshub_api:
    image: ${DOCKER_REGISTRY-}leadshubapi
    build:
      context: .
      dockerfile: Services/LeadsHub/LeadsHub.Api/Dockerfile

  whatsapp_api:
    image: ${DOCKER_REGISTRY-}whatsappapi
    build:
      context: .
      dockerfile: Integrations/WhatsApp/WhatsApp.Api/Dockerfile

