
using LeadsHub.Core.Enum;

namespace LeadsHub.Core.Models
{
    public sealed class LeadCard
    {
        /// <summary>
        /// Id to identify the consultant
        /// </summary>
        public long? ConsultantId { get; private set; }

        /// <summary>
        /// Consultant Name
        /// </summary>
        public string ConsultantName { get; private set; } = string.Empty;

        /// <summary>
        /// Company Id
        /// </summary>
        public long CompanyId { get; private set; }

        /// <summary>
        /// Date that it was registered in the system
        /// </summary>
        public DateTimeOffset CreatedAt { get; private set; }

        /// <summary>
        /// Lead identifier generated by the postgres uuid default
        /// </summary>
        public Guid Identifier { get; set; }

        /// <summary>
        /// Id to identify the lead
        /// </summary>
        public long LeadId { get; set; }

        /// <summary>
        /// The Name of the Lead
        /// </summary>
        public string LeadName { get; set; } = string.Empty;

        public string LastMessage { get; set; } = string.Empty;

        /// <summary>
        /// Last message time in the Message chat
        /// </summary>
        public DateTimeOffset LastMessageDate { get; private set; }

        /// <summary>
        /// Lead main phone number
        /// </summary>
        public string PhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// Lead main email
        /// </summary>
        public string Email { get; set; } = string.Empty;

        public string SaleNote { get; set; } = string.Empty;

        /// <summary>
        /// The status of the lead
        /// </summary>
        public LeadStatus Status { get; set; }

        public LeadPhase Phase { get; set; }

        public int TimelineId { get; set; }

        /// <summary>
        /// The Total of new messages in the lead chat
        /// </summary>
        public long TotalNewMessages { get; private set; }

        public string UserIdentityId { get; private set; } = string.Empty;
    }
}
