CREATE TABLE IF NOT EXISTS public."Company"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Identifier" uuid DEFAULT gen_random_uuid(),
    "BrandName" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "LegalName" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(400) COLLATE pg_catalog."default" NOT NULL,
    "Enabled" boolean NOT NULL DEFAULT false,
    "IdentificationNumber" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" character varying(20) COLLATE pg_catalog."default" NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Consultant"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdentityId" text COLLATE pg_catalog."default" NOT NULL,
    "FullName" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "NickName" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "PhotoUrl" text COLLATE pg_catalog."default" NOT NULL,
    "Enabled" boolean NOT NULL DEFAULT false,
    "TimeLastLeadAssigned" timestamp with time zone NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Consultant" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ConsultantCompany"
(
    "IdentityId" text COLLATE pg_catalog."default" NOT NULL,
    "ConsultantId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ConsultantCompany_IdentityId_ConsultantId_CompanyId_key" UNIQUE ("IdentityId", "ConsultantId", "CompanyId"),
    CONSTRAINT "ConsultantCompany_CompanyId_fkey" FOREIGN KEY ("CompanyId")
        REFERENCES public."Company" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "ConsultantCompany_ConsultantId_fkey" FOREIGN KEY ("ConsultantId")
        REFERENCES public."Consultant" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS public."Contact"
(
	"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
	"PhoneNumber" character varying(40) COLLATE pg_catalog."default" NOT NULL, 
	"Email" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
	"CPF" character varying(40) COLLATE pg_catalog."default" NOT NULL,
	"BirthDate" Date NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	CONSTRAINT "PK_Contact" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Address"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    "CompanyId" bigint NULL,
	"ContactId" bigint NULL,
    "Zipcode" text COLLATE pg_catalog."default" NOT NULL,
    "State" character varying(40) COLLATE pg_catalog."default" NOT NULL,
    "City" character varying(40) COLLATE pg_catalog."default" NOT NULL,
    "Street" character varying(400) COLLATE pg_catalog."default" NOT NULL,
    "Neighborhood" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Number" character varying(40) COLLATE pg_catalog."default" NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Address" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Address_Company_CompanyId" FOREIGN KEY ("CompanyId")
        REFERENCES public."Company" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT "FK_Address_Contact_ContactId" FOREIGN KEY ("ContactId")
        REFERENCES public."Contact" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."Lead"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Identifier" uuid DEFAULT gen_random_uuid(),
    "CompanyId" bigint NOT NULL,
    "ConsultantId" bigint NULL,
	"ContactId" bigint NULL,
	"CampaignId" bigint NULL,
    "IntegrationId" bigint NOT NULL,
    "AdCode" character varying(100) COLLATE pg_catalog."default" NULL,
    "Channel" int NULL,
	"Status" INT NOT NULL DEFAULT 1,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Lead" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lead_Company_CompanyId" FOREIGN KEY ("CompanyId")
        REFERENCES public."Company" ("Id") MATCH SIMPLE 
		ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT "FK_Lead_Contact_ContactId" FOREIGN KEY ("ContactId")
    	REFERENCES public."Contact" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public."MessageFile" 
(
	"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"MimeType" character varying(100) COLLATE pg_catalog."default" NULL,
	"Caption" character varying(1024) COLLATE pg_catalog."default" NULL,
    "Url" text COLLATE pg_catalog."default",
	CONSTRAINT "PK_MessageFile" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."MessageText" 
(
	"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Body" text NULL,
	CONSTRAINT "PK_MessageText" PRIMARY KEY ("Id")	
);

CREATE TABLE IF NOT EXISTS public."Timeline" 
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"LeadId" bigint NOT NULL,
	"ConsultantId" bigint NULL,
	"MessageTextId" bigint NULL,
	"MessageFileId" bigint NULL,
	"MessageId" text NULL,
	"Sender" smallint NOT NULL DEFAULT 1,
	"Type" smallint NOT NULL DEFAULT 1,
	"Status" smallint NOT NULL DEFAULT 1,
	"MessageDate" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"ReadAt" timestamp with time zone NULL,
   	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Timeline" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Timeline_Lead_LeadId" FOREIGN KEY ("LeadId") 
		REFERENCES "Lead"("Id")
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT "FK_Timeline_Consultant_ConsultantId" FOREIGN KEY ("ConsultantId")
        REFERENCES public."Consultant" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT "FK_Timeline_MessageText_MessageTextId" FOREIGN KEY ("MessageTextId")
    	REFERENCES public."MessageText" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT "FK_Timeline_MessageFile_MessageFileId" FOREIGN KEY ("MessageFileId")
    	REFERENCES public."MessageFile" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."MessageReaction" 
(
	"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"TimelineId" bigint NOT NULL,
	"Emoji" character varying(20) COLLATE pg_catalog."default" NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    "MessageId" text COLLATE pg_catalog."default",
	"UpdatedAt"  timestamp with time zone NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
	CONSTRAINT "PK_MessageReaction" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_MessageReaction_Timeline_TimelineId" FOREIGN KEY ("TimelineId")
    	REFERENCES public."Timeline" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."LastMessage" 
(
	"LeadId" bigint NOT NULL,
	"TimelineId" bigint NOT NULL,
	"LastMessage" text NOT NULL,
	"LastMessageDate" timestamp with time zone NOT NULL,
	"Status" smallint DEFAULT 1,
	CONSTRAINT "PK_LastMessage" PRIMARY KEY ("LeadId"),
	CONSTRAINT "FK_LastMessage_Lead_LeadId" FOREIGN KEY ("LeadId")
    	REFERENCES public."Lead" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT "FK_LastMessage_Timeline_TimelineId" FOREIGN KEY ("TimelineId")
    	REFERENCES public."Timeline" ("Id") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Maybe distinct service, so this will not have a foreign key
CREATE TABLE IF NOT EXISTS public."WhatsAppConfig"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "CompanyId" bigint NOT NULL,
	"PhoneNumberId" character varying(4000) COLLATE pg_catalog."default",
    "BusinessAccountId" character varying(4000) COLLATE pg_catalog."default",
    "AccessToken" text COLLATE pg_catalog."default",
    "WebHookSecret" text COLLATE pg_catalog."default",
    CONSTRAINT "WhatsAppConfig_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Integration"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "WhatsAppConfigId" bigint,
    CONSTRAINT "Integration_pkey" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Integration_WhatsAppConfig_WhatsAppConfigId" FOREIGN KEY ("WhatsAppConfigId")
    REFERENCES public."WhatsAppConfig" ("Id") MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE CASCADE
);