<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeadsHub.Core\LeadsHub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\Commands\20242112_Create_Tables.sql" />
  </ItemGroup>

</Project>
